config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :groups do
    resources :transactions
  end

  resources :users

  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Group, user: user
    can :manage, Expense, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def after_sign_up_path_for(_resource)
    groups_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/transactions_contoller.rb
class TransactionsController < ApplicationController
  before_action :set_group, only: %i[new create edit update destroy]
  before_action :set_transaction, only: %i[edit update destroy]
  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.group_id = @group.id

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @group, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @group, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to @group, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount).merge(user_id: current_user.id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_group, only: %i[new create edit update destroy]
  before_action :set_transaction, only: %i[edit update destroy]
  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.group_id = @group.id

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @group, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @group, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to @group, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  # GET /users or /users.json
  def index
    @users = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, value: @group.name, placeholder: "Name", required: true, class: "inputs" %>
  </div>

  <div class="select_icon">
    <%= form.label :icon, 'Select Icon:', class: "select_icon_label" %>
    <%= form.select :icon, ["👞","👔","🎵","🎉","🎄","🎁","🍼","✈️", "🎮", "📚", "🏥", "🏈", "🎬", "🏠", "🐶", "🍻", "🍔", "🚗", "🖥"], value: @group.icon, required: true, class: "select_icon_menu" %>
  </div>

  <div>
    <%= form.submit "Save Group", class: "actions-btn" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="group_card">
  <div class="group_card_left">
    <p class="category_icon"><%= group.icon %></p>
    <p class='color'><%= group.name %></p>
  </div>
  <p class='color'>$ <%= group.total_amount %></p>
</div>

app/views/groups/edit.html.erb
<%= render '/navbar' %>
<%= render "form", group: @group %>

app/views/groups/index.html.erb
<%= render '/navbar' %>

<p style="color: green; margin: 3px 30%;"><%= notice %></p>

<div class="cards_list">
  <% @groups.each do |group| %>
    <%= link_to group, class:"category-card" do %>
      <%= render group %>
    <% end %>
  <% end %>
</div>

<%= link_to "Add Category", new_group_path, class: "category_button" %>

app/views/groups/new.html.erb
<%= render '/navbar' %>
<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<%= render '/navbar' %>

<p style="color: green;margin: 3px 30%;"><%= notice %></p>

<div class='category-card'>
<%= link_to edit_group_path(@group) do %>
  <%= render @group %>
<% end %>
</div>


<div class='red-align'>
  <%= button_to "Remove Category", @group, method: :delete, class:'red' %>
</div>


<div>
  <h1 class='t-title'>Transactions<h1>
  <div class="cards_list">
    <%= render @group.transactions.order(created_at: :desc) %>
  </div>

  <%= link_to "New Transaction", new_group_transaction_path(@group), class: "category_button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

app/views/partials/_navback.html.erb
<%if current_user%>
  <% if current_page?(groups_path) %>
    <%= link_to root_path, class:"nav-btn" do %>
      <span class="iconify" data-icon="eva:arrow-back-fill"></span>
    <% end %>

  <% else %>
    <% if @group %>
      <% if @group.id == nil && current_page?(new_group_path) %>
        <%= link_to groups_path, class:"nav-btn" do %>
          <span class="iconify" data-icon="eva:arrow-back-fill"></span>
        <% end %>
      <% end %>

      <% if @group.id != nil && current_page?(group_path(@group)) %>
        <%= link_to groups_path, class:"nav-btn" do %>
          <span class="iconify" data-icon="eva:arrow-back-fill"></span>
        <% end %>
      <% end %>

      <% if @group.id != nil && current_page?(edit_group_path(@group)) %>
        <%= link_to group_path(@group), class:"nav-btn" do %>
          <span class="iconify" data-icon="eva:arrow-back-fill"></span>
        <% end %>
      <% end %>
    <% end %>

    <% if @transaction && @group %>
      <% if @transaction.id == nil && current_page?(new_group_transaction_path(@group)) %>
        <%= link_to group_path(@group), class:"nav-btn" do %>
          <span class="iconify" data-icon="eva:arrow-back-fill"></span>
        <% end %>
      <% end %>

      <% if @transaction.id != nil && current_page?(edit_group_transaction_path(@group, @transaction)) %>
        <%= link_to group_path(@group), class:"nav-btn" do %>
          <span class="iconify" data-icon="eva:arrow-back-fill"></span>
        <% end %>
      <% end %>
    <% end %>
    
  <% end %>

<% else %>
  <%= link_to root_path, class:"nav-btn" do %>
    <span class="iconify" data-icon="eva:arrow-back-fill"></span>
  <% end %>
<%end%>

app/views/partials/_navtitle.html.erb
<% if current_page?(new_user_session_path) %>
  Log In
<% end %>
<% if current_page?(new_user_registration_path) %>
  Sign Up
<% end %>
<% if current_page?(new_user_password_path) %>
  Forgot Password
<% end %>
<% if @group %>
  <% if @group.id == nil && current_page?(new_group_path) %>
    New Category
  <% end %>
  <% if @group.id != nil && current_page?(group_path(@group)) %>
    <%= @group.name.upcase %>
  <% end %>
  <% if @group.id != nil && current_page?(edit_group_path(@group)) %>
    Edit Category
  <% end %>
<% end %>
<% if @transaction && @group %>
  <% if @transaction.id == nil && current_page?(new_group_transaction_path(@group)) %>
    New Transaction
  <% end %>
  <% if @transaction.id != nil && current_page?(edit_group_transaction_path(@group, @transaction)) %>
    Edit Transaction
  <% end %>
<% end %>
<% if current_page?(groups_path) %>
  Categories
<% end %>

app/views/transactions/_form.html.erb
<%= form_with(model: [@group, @transaction]) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: 'Name', class:'inputs' %>
  </div>

  <div>
   <%= form.text_field :amount, placeholder: 'Amount in $', class:'inputs' %>
  </div>

  <div>
    <%= form.submit "Save Transaction", class:'actions-btn' %>
  </div>
<% end %>


<div class="red-align">
  <% if @transaction.id != nil && current_page?(edit_group_transaction_path(@group, @transaction)) %>
    <%= button_to "Delete transaction", group_transaction_path(@group, @transaction), method: :delete, class: "red" %>
  <% end %>
</div>

app/views/transactions/_transaction.hrml.erb
 <%= link_to edit_group_transaction_path(@group, transaction), class:"card_link" do %>
  <div class="group_card">
    <p class='color'><%= transaction.name %></p>
    <p class='color'>$ <%= transaction.amount %></p>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
 <%= link_to edit_group_transaction_path(@group, transaction), class:"card_link" do %>
  <div class="group_card">
    <p class='color'><%= transaction.name %></p>
    <p class='color'>$ <%= transaction.amount %></p>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<%= render '/navbar' %>
<%= render "form", transaction: @transaction %>

app/views/transactions/new.html.erb
<%= render '/navbar' %>
<%= render "form", transaction: @transaction %>

app/views/users/index.html.erb
<div class='main-container'>
  <%if current_user%>
    <h2 class="welcome">Welcome, <%= current_user.name %>!</h2>
  <% end %>
<div class='main-btns'>
  <%if current_user%>
    <%= link_to "Categories", groups_path, class:"log-in" %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"sign-up" %>
  <% else %>
    <%= link_to "Log In", new_user_session_path, class:"log-in" %>
    <%= link_to "Sign Up", new_user_registration_path, class:"sign-up" %>
  <% end %>
</div>

<p class='developed'>By: <a href="https://github.com/isaacpitwa"target="_blank" rel="noopener noreferrer">Isaac Pitwa</a></p>

</div>